### ISSUE TITLE
request for --yaml option

### ISSUE THREAD

**Issue by cbm755** [johannesjh/req2flatpak#37]
Low priority and I guess I don't have a strong argument for yaml, except that `flatpak-pip-generator` has it (also via `--yaml`) and I prefer reading yaml over JSON.

(Thanks for this project, works great and will save me a lot of time!)

**Comment by johannesjh** [comment]
hi Colin, thank you for your positive feedback and thank you for this suggestion. Would you want to submit this as pull request?

Some design considerations / suggestions:

- poetry dependencies: the `pyyaml` dependency should be optional, i.e., an "extra" dependency in poetry. 
- commandline option: you could add a `--format` or `-f` commandline parameter, defaulting to `json`, optionally `yaml`. 
- handling import errors: the script should still be able to produce json, even if `pyyaml` has not been installed. you could import pyyaml locally, i.e. in the method where you need it instead of at the beginning of the file. you could wrap the import statement in a try/catch block. 
- yaml serialization: req2flatpak currently has only one method `build_module_as_str` which serializes to a json string. you could create two different methods instead, one for json and another one for yaml serialization.
- testing: a test case to make sure that yaml output is produced
- documentation: a section in `cli.rst` to describe the new commandline option

**Comment by cbm755** [comment]
I might have a chance to take a look next time I'm bumping deps on my flatpak.

Your step-by-step looks very well-thought out: I agree "good first issue" for someone looking to get involved: I'll certainly not be offended if someone does it first, and will be happy to test.
