### ISSUE TITLE
`make test` fails: Poetry configuration is invalid: Additional properties are not allowed ('group' was unexpected)

### ISSUE THREAD

**Issue by cbm755** [johannesjh/req2flatpak#43]
I'm on Fedora.  I did:
  - `dnf install poetry` (never used this before, I know its probably better, etc etc but I'm slow to adopt new things)
  - `dnf install pre-commit`.  
  - `pip install pylama`

When I try `make test`, I get:

```
poetry run python3 -m unittest

  RuntimeError

  The Poetry configuration is invalid:
    - Additional properties are not allowed ('group' was unexpected)
  

  at /usr/lib/python3.11/site-packages/poetry/core/factory.py:43 in create_poetry
       39│             message = ""
       40│             for error in check_result["errors"]:
       41│                 message += "  - {}\n".format(error)
       42│ 
    →  43│             raise RuntimeError("The Poetry configuration is invalid:\n" + message)
       44│ 
       45│         # Load package
       46│         name = local_config["name"]
       47│         version = local_config["version"]
make: *** [Makefile:11: test] Error 1
```

**Comment by cbm755** [comment]
I uninstalled my distro-provided poetry and did `pip install poetry`, which got me:
```
$ poetry --version
Poetry (version 1.3.2)
```

Now `make test` works:
```
$ make test
poetry run python3 -m unittest
.....................
----------------------------------------------------------------------
Ran 21 tests in 1.979s

OK
```

- - - -

Is is possible to declare a minimum value of `poetry`?

**Comment by johannesjh** [comment]
Hi, glad you got it working! By the way, the [recommended way to install poetry](https://python-poetry.org/docs/#installation) uses their install script or `pipx` instead of pip because this will keep the packages needed by poetry separate from the packages of your system user.

> Is it possible to declare a minimum version of poetry?

Unfortunately no, I don't think so, judging from a quick search online, see: [How to enforce a minimum python poetry version](https://stackoverflow.com/q/64003868) and the linked ticket [poetry #3316](https://github.com/python-poetry/poetry/issues/3316)
